#!/bin/bash
# ============================================================
# Microgrid Data Pusher — Raspberry Pi Setup
# ============================================================
# Run on the Pi AFTER install.sh and after the server is set up.
#
# Usage:  bash install_pusher.sh YOUR_API_KEY
# ============================================================

set -e

if [ -z "$1" ]; then
    echo "Usage: bash install_pusher.sh YOUR_API_KEY"
    echo ""
    echo "  The API key is generated by install_server.sh on the server."
    exit 1
fi

API_KEY="$1"
INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VENV_DIR="$INSTALL_DIR/venv"

echo "============================================"
echo " Data Pusher — Setup"
echo "============================================"

# --- Ensure venv exists and has requests ---
if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_DIR"
fi

source "$VENV_DIR/bin/activate"
pip install --upgrade pip
pip install requests

# --- Systemd service ---
echo "Installing systemd service..."

SERVICE_FILE="/etc/systemd/system/microgrid-pusher.service"
sudo tee "$SERVICE_FILE" > /dev/null <<SERVICEEOF
[Unit]
Description=Microgrid Data Pusher (Pi → Server)
After=network-online.target solis-monitor.service
Wants=network-online.target solis-monitor.service

[Service]
Type=simple
User=$USER
WorkingDirectory=$INSTALL_DIR
Environment=MONITOR_API_KEY=$API_KEY
ExecStart=$VENV_DIR/bin/python data_pusher.py --server-url https://monitor.mooramoora.org.au --api-key $API_KEY --interval 60
Restart=always
RestartSec=30
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SERVICEEOF

sudo systemctl daemon-reload
sudo systemctl enable microgrid-pusher.service
sudo systemctl start microgrid-pusher.service

echo ""
echo "============================================"
echo " Data pusher installed and started!"
echo "============================================"
echo ""
echo " Commands:"
echo "   sudo systemctl status microgrid-pusher   # Check status"
echo "   sudo journalctl -u microgrid-pusher -f   # View logs"
echo "   sudo systemctl restart microgrid-pusher   # Restart"
echo ""
